In [135]:
import tensorflow as tf
import numpy as np
from numpy import random, argmax
from tictactoe_train import *

In [137]:
memories = read_data()
print("\n".join(map(str,memories[:50])))

[array([[-1,  0,  1,  0,  1,  0,  0,  0,  0]]), array([[ 0,  0,  0,  0, -1,  0,  0,  0,  0]])]
[array([[ 1,  0, -1,  0, -1,  0,  0,  0,  0]]), array([[ 0,  0,  0,  0, -1,  0,  0,  0,  0]])]
[array([[-1,  0,  1,  0,  1,  0,  0,  0,  0]]), array([[ 0,  0,  0,  0, -1,  0,  0,  0,  0]])]
[array([[ 1,  0, -1,  0, -1,  0,  0,  0,  0]]), array([[ 0,  0,  0,  0, -1,  0,  0,  0,  0]])]
[array([[-1,  0,  1,  0,  1,  0,  0, -1,  0]]), array([[ 0,  0,  0,  0,  0,  0,  0, -1,  0]])]
[array([[ 1,  0, -1,  0, -1,  0,  0,  1,  0]]), array([[ 0,  0,  0,  0,  0,  0,  0, -1,  0]])]
[array([[-1,  0,  1,  0,  1,  0,  0, -1,  0]]), array([[ 0,  0, -1,  0,  0,  0,  0,  0,  0]])]
[array([[ 1,  0, -1,  0, -1,  0,  0,  1,  0]]), array([[ 0,  0, -1,  0,  0,  0,  0,  0,  0]])]
[array([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), array([[0, 0, 1, 0, 0, 0, 0, 0, 0]])]
[array([[-1,  0,  1,  0,  0,  0,  0,  0,  0]]), array([[0, 0, 0, 0, 1, 0, 0, 0, 0]])]
[array([[-1,  0,  1,  0,  1,  0,  0, -1,  0]]), array([[0, 0, 0, 0, 0, 0, 1, 

In [138]:
def add_layer(inputs, in_size, out_size, activation_function = None):
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)
    Wx_plus_b = tf.matmul(inputs, Weights) + biases
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs

In [146]:
def validTest():
    for _ in range(10):
        player1_num = randint(1,4)
        player2_num = player1_num + choice([0, -1])

        grid = [0 for _ in range(9)]

        for _ in range(player1_num):
            choices = [i for i in range(9) if grid[i] == 0]

            grid[choice(choices)] = 1

        for _ in range(player2_num):
            choices = [i for i in range(9) if grid[i] == 0]

            grid[choice(choices)] = -1

        grid = array(grid)
        pre = sess.run(prediction, feed_dict={xs:[grid]})
        print(grid)
        print(argmax(pre[0]))

In [147]:
x_data = [m[0][0] for m in memories]
y_data = [m[1][0] for m in memories]

In [148]:
xs = tf.placeholder(tf.float32, [None, 9])
ys = tf.placeholder(tf.float32, [None, 9])

In [149]:
l1 = add_layer(xs, 9, 18, tf.nn.relu)
l2 = add_layer(l1, 18, 36, tf.nn.relu)
prediction = add_layer(l2, 36, 9)

loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys - prediction), reduction_indices=[1]))
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)



In [150]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [151]:
for i in range(1000):
    sess.run(train_step, feed_dict={xs: x_data, ys: y_data})
    if i % 50 == 0:
        print(sess.run(loss, feed_dict={xs: x_data, ys: y_data}))

3.4642e+10
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan


In [152]:
validTest()

[ 0  1 -1  0  1 -1 -1  1  1]
0
[-1 -1 -1  1  1 -1  1  0  1]
0
[0 0 0 1 0 0 0 0 0]
0
[0 0 1 0 0 0 0 0 0]
0
[ 0  1  0  0 -1  0  1  0  0]
0
[ 0  0  1  0 -1  1  0 -1  0]
0
[ 1  0  0 -1  1  0 -1  1 -1]
0
[ 1  0  0  0  0  1  0 -1  0]
0
[ 0 -1  0  0  0  1  1  0  0]
0
[1 0 0 0 0 0 0 0 0]
0
